name: generate cv/resume
on:
  push:
    branches:
      - master
jobs:
  build:
    name: generate
    runs-on: alpine-latest
    inputs:
      - input-file: cv.tex
    steps:
      - name: generate
        uses: marcomicera/xelatex-action@v0.6
