name: generate cv/resume
on:
  push:
    branches:
      - master
jobs:
  build:
    name: generate
    steps:
      - name: generate
        uses: marcomicera/xelatex-action@v0.6
        with:
          input-file: cv.tex
