name: generate cv/resume
on:
  push:
    branches:
      - master
jobs:
  build:
    name: generate
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@latest
      - name: compile latex to pdf
        uses: dante-ev/latex-action@latest
        with:
          compiler: xelatex
          root_file: cv.tex
      - name: archive generated pdf document
        uses: actions/upload-artifact@v3
        with:
          name: piotr_wittchen_cv.pdf
          path: cv.pdf
