name: generate cv/resume
on:
  push:
    branches:
      - master
jobs:
  build:
    name: generate
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: compile latex
        uses: dante-ev/latex-action@latest
        with:
          root_file: cv.tex
